import { isProtectedWorldId } from "./tellus-world-options";

export const LEGACY_WORLD_CLEANUP_IDS = [
  "agent-test",
  "aurora-test",
  "blue-clouds-test",
  "chunked-24-alien-spires",
  "chunked-24-copper-terrace",
  "chunked-24-coral-archipelago",
  "chunked-24-coral-canyon",
  "chunked-24-grand-canyon",
  "chunked-24-testbiomes",
  "chunked-64-agent-test",
  "chunked-64-aurora-test",
  "chunked-64-blue-clouds-test",
  "chunked-64-cahokia",
  "chunked-64-chaco-canyon",
  "chunked-64-copy-of-main",
  "chunked-64-desert-test-1",
  "chunked-64-dick",
  "chunked-64-genesis",
  "chunked-64-giant",
  "chunked-64-holo-test",
  "chunked-64-large-world",
  "chunked-64-lisa-test-door",
  "chunked-64-probe-1781244360",
  "chunked-64-starry-night-test",
  "chunked-64-thin-probe",
  "chunked-64-wo16probe",
  "desert-test-1",
  "dick",
  "giant",
  "holo-test",
  "infinity-demo",
  "interior-chunked-24-copper-terrace-room_mqu5sd7",
  "interior-chunked-64-genesis-room_mqn713p",
  "interior-chunked-64-genesis-room_mqwrza3",
  "interior-chunked-64-genesis-room_mqws2t3",
  "interior-chunked-64-large-world-room_mquogjy",
  "interior-chunked-64-main-room_mqugf8e",
  "interior-chunked-64-main-room_mquhy3s",
  "interior-chunked-64-thin-probe-room_mqu5i36",
  "interior-infinity-demo-tavern",
  "interior-main-room_mqn0oe2",
  "large-world",
  "lisa-test-door",
  "private-rjs",
  "probe-1781244360",
  "ptest-1781057493",
  "starry-night-test",
  "thin-probe",
  "wo16probe",
  "zzz",
] as const;

export function validatedLegacyWorldCleanupIds(): string[] {
  return [...new Set(LEGACY_WORLD_CLEANUP_IDS)]
    .filter((worldId) => !isProtectedWorldId(worldId))
    .sort();
}
